import { YoutubeApiData } from "../index"


function extractInnertubeApiKey() {
  const pattern = '"INNERTUBE_API_KEY":\s*"([a-zA-Z0-9_-]+)"'

  return document.documentElement.innerHTML.match(pattern).at(1)
}

async function fetchInnertubeData(videoId: string) {
  const apiKey = extractInnertubeApiKey()

  const r = await fetch('https://www.youtube.com/youtubei/v1/player?key=' + apiKey, {
    body: JSON.stringify({
      context: { client: { clientName: 'ANDROID', clientVersion: '20.10.38' } },
      videoId,
    }),
    method: 'POST',
  })

  return await r.json()
}

export async function getTranscript(englishFirst = false) {
  const videoId = new URLSearchParams(window.location.search).get('v')

  if (!videoId) {
    throw "Couldn't get video id"
    return
  }

  const data: YoutubeApiData = await fetchInnertubeData(videoId)


  if (data.captions === undefined) {
    throw "Looks like this video doesn't have captions or we had trouble fetching them"
  }

  const captions = data.captions.playerCaptionsTracklistRenderer

  let captionTrack: typeof captions.captionTracks[number] | undefined

  if (englishFirst) {
    captionTrack = captions.captionTracks.find(t => t.languageCode === 'en' || t.vssId?.includes('a.en'))
    
    if (!captionTrack) {
      const autoGenerated = captions.captionTracks.find(t => t.vssId?.startsWith('a.'))
      if (autoGenerated) {
        captionTrack = autoGenerated
      } else if (captions.captionTracks.length > 0) {
        captionTrack = captions.captionTracks[0]
      }
    }
  } else {
    let defaultCaptionLanguage = captions.audioTracks[0].defaultCaptionTrackIndex ?? captions.defaultAudioTrackIndex ?? 0

    if (defaultCaptionLanguage > captions.captionTracks.length - 1) {
      defaultCaptionLanguage = 0
    }

    captionTrack = captions.captionTracks[defaultCaptionLanguage]
  }

  if (!captionTrack) {
    throw "No captions available for this video"
  }

  const captionsUrl = new URL(captionTrack.baseUrl)
  captionsUrl.searchParams.set("fmt", "") // return basic xml

  const r = await fetch(captionsUrl)

  const xmlText = await r.text()

  // Parse XML to DOM
  const parser = new DOMParser()

  const xml = parser.parseFromString(xmlText, 'text/xml')
  const entityParser = new DOMParser()

  let transcription = ''

  for (const caption of xml.getElementsByTagName('text')) {
    const escapedText = caption.textContent ?? ''
    const time = Number(caption.getAttribute('start'))
    const doc = entityParser.parseFromString(`<root>${escapedText}</root>`, 'text/xml')
    const text = doc.documentElement.textContent || ''

    if (time) {
      transcription += `[${Math.floor(time)}s]\n`
    }

    transcription += text + '\n'
  }

  return transcription
}
